config/routes.rb
LivingDeadReviews::Application.routes.draw do

  get "home/index"
  root :to => 'home#index'
  
  devise_for :users

  resources :products do
    resources :reviews
  end 

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  attr_accessible :model_number, :name
  validates :model_number, :presence => true
  validates :name, :presence => true
  
  def active_reviews
    reviews.find(:all, :conditions => { :status => "active"})
  end
  
  def average_rating
    reviews.collect(&:rating).sum.to_f/reviews.length if reviews.length > 0
  end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  attr_accessible :comment, :product_id, :rating, :status, :user_email, :user_id
  validates :rating, :presence => true
  validates :comment, :presence => true
  validates :user_email, :presence => true
  validates_uniqueness_of :product_id, :scope => :user_id, :message => "has already been reviewed"
  validates :rating, :numericality => { :greater_than => 0, :less_than_or_equal_to => 5}
  
  def strip_comment
    comment.gsub(%r{</?[^>]+?>}, '')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validates :email, :presence => true
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.sort_by{|product| product.average_rating.nil? ?  0.0 : product.average_rating}.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  # GET /reviews
  # GET /reviews.json
  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end
  
  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end


  # POST /reviews
  # POST /reviews.json
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.build(params[:review].merge(:user_id => current_user.id))
    @review.comment = @review.strip_comment

    respond_to do |format|
      if @review.save
        format.html { render action: "index", notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to product_reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<h1>Welcome to Living Dead Reviews!</h1>
<p>Tired of inferior weapons breaking off in your zombie's head?  Find the best products here!</p>
<%= link_to 'View Products', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LivingDeadReviews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="user_nav">
    <ul>
      <li>
        <%= link_to "Home", home_index_path%> |
      </li>
      <% if user_signed_in? %>
        <li>
            <%= link_to "Create Product Listing", new_product_path %> |
        </li>
      <% end %>
      <li>
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
      </li>
    </ul>
  </div>

  <div id = "content">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br />
    <%= f.number_field :model_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Model number</th>
    <th>Average Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.model_number %></td>
    <td><%= product.average_rating %></td>
    <td><%= link_to 'Write Review', new_product_review_path(:product_id => product.id) %></td>
    <td>| <%= link_to 'View Reviews', product_reviews_path(:product_id => product.id)%></td>
  </tr>
<% end %>
</table>

<br />

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Model number:</b>
  <%= @product.model_number %>
</p>
<%= link_to 'View Products', products_path %>

app/views/reviews/_form.html.erb
<%= form_for([@product,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br />
    <%= f.text_field :user_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', product_reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= @product.name %></h1>

<table>
  <tr>
    <th>Rating</th>
    <th>Comment</th>
    <th>User email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product.active_reviews.each do |review| %>
  <tr>
    <td><%= review.rating %></td>
    <td><%= review.comment %></td>
    <td><%= review.user_email %></td>
  </tr>
<% end %>
</table>
<%= link_to 'View Products', products_path %>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', product_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>

<p>
  <b>User email:</b>
  <%= @review.user_email %>
</p>

<%= link_to 'Back', product_reviews_path %>